language: node_js
node_js:
- 5
sudo: false
addons:
  firefox: latest
  apt:
    packages:
    - oracle-java8-installer
    - oracle-java8-set-default
before_script:
- npm run test:lint:js
- npm run test:lint:html
script:
- xvfb-run wct
